kind = "web"
previewPath = "/"
title = "Aimstorm Internship"
version = "1.0.0"
id = "artifacts/aimstorm"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24259

[services.development]
run = "pnpm --filter @workspace/aimstorm run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/aimstorm", "run", "build" ]
publicDir = "artifacts/aimstorm/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24259"
BASE_PATH = "/"
